version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 351659483310.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t project-repo .
      - docker tag project-repo:latest 351659483310.dkr.ecr.us-west-2.amazonaws.com/project-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 351659483310.dkr.ecr.us-west-2.amazonaws.com/project-repo:latest
      - printf '[{"name":"frontendContainer","imageUri":"%s"}]' 351659483310.dkr.ecr.us-west-2.amazonaws.com/project-repo:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
