/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:66fa95e1-6539-4fbb-ae51-8d11ab4689fc",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_vn3nVqbWz",
    "aws_user_pools_web_client_id": "3701eg95eogd0gt1ols0kbl36d",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "amazon_location_service": {
            "region": "us-west-2",
            "search_indices": {
                "items": [
                    "placeindex3b20cfb4-dev"
                ],
                "default": "placeindex3b20cfb4-dev"
            },
            "maps": {
                "items": {
                    "ProjectFrontendMap-dev": {
                        "style": "VectorEsriStreets"
                    },
                    "ProjectMap-dev": {
                        "style": "VectorEsriStreets"
                    }
                },
                "default": "ProjectMap-dev"
            }
        }
    }
};


export default awsmobile;
